# Generated by Django 4.2.6 on 2023-10-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('per_kg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='consumer', max_length=16),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.price')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.user')),
            ],
        ),
    ]
