# Generated by Django 4.2.6 on 2023-10-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_role_remove_user_role_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='farm_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendapp.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('delivery_days', models.CharField(max_length=64)),
                ('delivery_time', models.CharField(max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.user')),
            ],
        ),
    ]
