# Generated by Django 4.2.6 on 2023-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_remove_post_user_id_post_farm_id_post_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Farma zajebista', max_length=400),
            preserve_default=False,
        ),
    ]
