# Generated by Django 4.2.6 on 2023-10-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.farm'),
        ),
    ]
