# Generated by Django 4.2.6 on 2023-10-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0010_user_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFarmsRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.area')),
            ],
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farms_group_id',
        ),
        migrations.DeleteModel(
            name='AreaFarmsGroup',
        ),
        migrations.AddField(
            model_name='areafarmsrelation',
            name='farms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.farm'),
        ),
    ]
