# Generated by Django 4.2.6 on 2023-10-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_areafarmsrelation_remove_farm_farms_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='amount',
            new_name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='price',
            name='weight',
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('per_kg', models.BooleanField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.farm')),
                ('order_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.orderinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.user')),
            ],
        ),
    ]
